[project]
name = "wg-port-checker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nat-pmp>=1.3.2",
    "requests>=2.32.5",
]
